version: 2.1
jobs:
  build_test_auth:
    working_directory: ~/Creating-and-Testing-Microservices/auth
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout:
          path: ~/Creating-and-Testing-Microservices
      - run:
          name: update npm
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run test
          command: npm test

  build_test_users:
    working_directory: ~/Creating-and-Testing-Microservices/users
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout:
          path: ~/Creating-and-Testing-Microservices
      - run:
          name: update npm
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: sudo npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: run test
          command: npm test

workflows:
  version: 2
  build-test-services:
    jobs:
      - build_test_auth
      - build_test_users:
          requires:
            - build_test_auth
